"""Contract-driven CMD background execution runtime."""

from .adapters import (
    AdapterCoverage,
    AdapterError,
    CapabilityAdapters,
    HttpWebTransport,
    ResidentGoogleTransport,
    ResidentHotmailTransport,
)
from .capabilities import CapabilityRegistry, PolicyDecision, PolicyDenial, RegistryError
from .control import CmdControlPlane, IntakeResult, ShadowReplayRecord
from .context_resolver import ContextResolution, resolve_context
from .local_context import load_local_context_catalog
from .broker import BrokerDenied, CapabilityBroker, JobToolProxy, canonical_payload_hash
from .jobspec import (
    CompiledJob,
    ContextRef,
    JobSpec,
    JobSpecError,
    compile_job,
    materialize_job,
    parse_job_spec,
)
from .leases import LeaseError, LeaseSigner, VerifiedLease
from .resolution import (
    ExecutionResolution,
    OutcomeResolution,
    ResolutionDecision,
    ResolutionDenial,
    ResolutionPlan,
    ResolutionPlanError,
    ResolverRegistry,
    ResolverRegistryError,
    canonicalize_resolution_plan,
    parse_resolution_plan,
)
from .resolution_planner import (
    ResolutionAttempt,
    ResolutionCompilationError,
    ResolutionRequestError,
    build_resolution_prompt,
    compile_validated_dispatch,
    resolve_registry_request,
)
from .evaluation import (
    ContractRunner, EvaluationError, ManifestSigner, NamespaceGuard,
    ReliabilityCase, TestRunManifest, load_corpus, write_report,
)
from .sandbox import (
    ExecutionResult,
    RuntimePacket,
    SafehouseExecutor,
    SandboxError,
    claude_command,
    codex_command,
    prepare_runtime,
    safehouse_prefix,
)
from .state import ClaimedRun, JobStateStore, StateError, provider_idempotency_key
from .verifier import (
    Evidence,
    VerificationReport,
    aggregate_verification,
    run_semantic_review,
    semantic_review_packet,
    verify_file,
    verify_provider_artifact,
    verify_sqlite_row,
)

__all__ = [
    "AdapterCoverage",
    "AdapterError",
    "CapabilityAdapters",
    "CapabilityRegistry",
    "ClaimedRun",
    "CmdControlPlane",
    "Evidence",
    "ExecutionResult",
    "ExecutionResolution",
    "BrokerDenied",
    "CapabilityBroker",
    "CompiledJob",
    "ContextRef",
    "ContextResolution",
    "load_local_context_catalog",
    "JobSpec",
    "JobSpecError",
    "JobStateStore",
    "JobToolProxy",
    "HttpWebTransport",
    "IntakeResult",
    "OutcomeResolution",
    "ShadowReplayRecord",
    "LeaseError",
    "LeaseSigner",
    "ContractRunner",
    "EvaluationError",
    "ManifestSigner",
    "NamespaceGuard",
    "ReliabilityCase",
    "ResolutionDecision",
    "ResolutionDenial",
    "ResolutionPlan",
    "ResolutionPlanError",
    "ResolutionAttempt",
    "ResolutionCompilationError",
    "ResolutionRequestError",
    "ResolverRegistry",
    "ResolverRegistryError",
    "TestRunManifest",
    "load_corpus",
    "write_report",
    "PolicyDecision",
    "PolicyDenial",
    "RegistryError",
    "ResidentGoogleTransport",
    "ResidentHotmailTransport",
    "RuntimePacket",
    "SafehouseExecutor",
    "SandboxError",
    "StateError",
    "VerifiedLease",
    "VerificationReport",
    "aggregate_verification",
    "canonical_payload_hash",
    "canonicalize_resolution_plan",
    "claude_command",
    "codex_command",
    "provider_idempotency_key",
    "prepare_runtime",
    "run_semantic_review",
    "semantic_review_packet",
    "safehouse_prefix",
    "verify_file",
    "verify_provider_artifact",
    "verify_sqlite_row",
    "compile_job",
    "resolve_context",
    "materialize_job",
    "parse_job_spec",
    "parse_resolution_plan",
    "build_resolution_prompt",
    "compile_validated_dispatch",
    "resolve_registry_request",
]
